### ISSUE TITLE
Cannot set property 'info' of undefined

### ISSUE THREAD

**Issue by maxfriedmann** [ben-eb/grunt-available-tasks#25]
Hi,
I recently updated to version 0.6.0 and am now getting the following error : 

´´´
D:\something>grunt --stack
Running "availabletasks:tasks" (availabletasks) task
Warning: Cannot set property 'info' of undefined Use --force to continue.
TypeError: Cannot set property 'info' of undefined
    at D:\something\node_modules\grunt-available-tasks\tasks\available_tasks.js:37:23
    at Array.forEach (native)
    at Object.<anonymous> (D:\something\node_modules\grunt-available-tasks\tasks\available_tasks.js:35:43)
    at Object.<anonymous> (D:\something\node_modules\grunt\lib\grunt\task.js:264:15)
    at Object.thisTask.fn (D:\something\node_modules\grunt\lib\grunt\task.js:82:16)
    at Object.<anonymous> (D:\something\node_modules\grunt\lib\util\task.js:301:30)
    at Task.runTaskFn (D:\something\node_modules\grunt\lib\util\task.js:251:24)
    at Task.<anonymous> (D:\something\node_modules\grunt\lib\util\task.js:300:12)
    at D:\something\node_modules\grunt\lib\util\task.js:227:11
    at process._tickCallback (node.js:355:11)
´´´

I am using the 'descriptions' option to override the default messages! From looking at the source it seems like (one of) my tasks cannot be found anymore? 

The latest task I added is a custom task.

**Comment by ben-eb** [comment]
Thanks for the report, fixed in 0.6.1. :smile:

**Comment by maxfriedmann** [comment]
Hehe, right! I missed defining the task, omg!

Many thanks, great work!
