### ISSUE TITLE
Cannot find module 'grunt-available-tasks/node_modules/underscore.string'

### ISSUE THREAD

**Issue by art0rz** [ben-eb/grunt-available-tasks#28]
Grunt fails with this error:
```
> grunt ts --verbose
Initializing
Command-line options: --verbose

Reading "Gruntfile.js" Gruntfile...OK

Registering Gruntfile tasks.
Reading package.json...OK
Parsing package.json...OK
Loading "Gruntfile.js" tasks...ERROR
>> Error: Cannot find module 'grunt-available-tasks/node_modules/underscore.string'
>>     at Function.Module._resolveFilename (module.js:339:15)
>>     at Function.Module._load (module.js:290:25)
>>     at Module.require (module.js:367:17)
>>     at require (internal/module.js:16:19)
>>     at Object.<anonymous> (D:\xampp\htdocs\sirin-solarin.teaser\tools\build\grunt\availabletasks.js:1:72)
>>     at Module._compile (module.js:413:34)
>>     at Object.Module._extensions..js (module.js:422:10)
>>     at Module.load (module.js:357:32)
>>     at Function.Module._load (module.js:314:12)
>>     at Module.require (module.js:367:17)

Running tasks: ts
Warning: Task "ts" not found. Use --force to continue.

Aborted due to warnings.
```

Using:
* node `v5.10.0`
* npm `3.8.3`
* grunt `0.4.5`
* available-tasks `0.6.0`

My gruntfile:

```
module.exports = function (grunt)
{
        setupGruntTime(grunt);

        var pkg = grunt.file.readJSON('package.json');
        var path = require('path');

        var sourceDir = 'deploy/htdocs/version/src/';
        var buildDir = 'build/';
        var buildVersionDir = 'build/version/';
        var gruntDir = path.normalize(process.cwd() + '/');
        var version = pkg.appversion;
        var appName = pkg.appname;
        var exportSourceMaps = true;
        var base = '../../';

        grunt.config('version', version);
        grunt.config('sourceDir', sourceDir);
        grunt.config('base', base);

        require('load-grunt-config')(grunt, {

                //auto grunt.initConfig
                init: true,

                //data passed into config.  Can use with <%= test %>
                data: {
                        sourceDir: sourceDir,
                        buildDir: buildDir,
                        buildVersionDir: buildVersionDir,
                        gruntDir: gruntDir,
                        version: version,
                        appName: appName,
                        exportSourceMaps: exportSourceMaps
                },

                // auto-loads tasks when needed, instead of by default
                jitGrunt: {
                        // here you can pass options to jit-grunt (or just jitGrunt: true)
                        customTasksDir: 'tasks',
                        pluginsRoot: 'tools/build/node_modules',
                        staticMappings: {
                                availabletasks: 'grunt-available-tasks',
                                scsslint: 'grunt-scss-lint'
                        }
                }
        });

        // change base so tasks don't have to '../'
        grunt.file.setBase(base);
};
```

Edit: formatting

**Comment by ben-eb** [comment]
Perhaps your install didn't complete correctly? Could you try `npm i underscore.string` please?

**Comment by art0rz** [comment]
It completed correctly. underscore.string is installed.

When I copy the `underscore.string` directory to `node_modules/grunt-available-tasks/node_modules` it works.

**Comment by ben-eb** [comment]
OK. I can't reproduce with a fresh install, so I think the problem is npm.
